name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: solver
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Black check
        working-directory: solver
        run: black --check src test

      - name: isort check
        working-directory: solver
        run: isort --check-only src test

      - name: Flake8 lint
        working-directory: solver
        run: flake8 src test
